version: 2.1
jobs:
  build:
    docker:
      - image: g33tha/plugin:latest
        environment:
           framework_version_number: $CIRCLE_BRANCH
           editorType: contentEditor
           editor_version_number: $CIRCLE_BRANCH
           CHROME_BIN: google-chrome
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      
      - run: npm install
      - run: cd app
      - run: bower cache clean
      - run: bower prune -f 
      - run: bower install --force -V
      - run: cd ..
      - run: gulp packageCorePlugins
      - run: npm run build-plugins
      - run: npm run build
      - store_artifacts:
          path: content-editor.zip
          destination: content-editor.zip
          
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths: ./node_modules

workflows:
  version: 2.1
  build_and_test:
    jobs:
      - build
          
          
