language: node_js
node_js:
    - "6.1"
sudo: required
addons:
  chrome: stable
before_script:
    - npm install
    - cd app
    - npm install -g bower
    - bower cache clean
    - bower install --force
    - npm run build
script:
    - npm run testpluginframework