version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node:6.10-browsers
        environment:
           framework_version_number: $CIRCLE_BRANCH
           editorType: contentEditor
           editor_version_number: $CIRCLE_BRANCH
           #CHROME_BIN: google-chrome
    steps:
      - checkout
      #- restore_cache:
          #key: dependency-cache-{{ checksum "package.json" }}
      - run: git clone https://github.com/project-sunbird/sunbird-content-plugins.git plugins -b $CIRCLE_BRANCH 
      - run: npm install
      - run: cd app && bower cache clean --allow-root
      - run: cd app && bower prune -f --allow-root
      - run: cd app && bower install --force -V --allow-root
      - run: gulp packageCorePlugins
      - run: npm run build-plugins
      - run: npm run build
      
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths: ./node_modules
      - run: 
          name: test-with-coverage
          command: 'mkdir -p /tmp/logs && npm run test-with-coverage | tee /tmp/logs/test_cases.log'
      - run:
          name: Publishing report to Codacy
          command: 'npm install -g codacy-coverage && cat ./coverage/lcov.info | codacy-coverage '
          when: always
       
      - store_artifacts:
          path: /tmp/logs
          destination: logs 
    
    
workflows:
  version: 2.1
  build_and_test:
    jobs:
      - build
